Crucible | rename cluster output to avoid conflicts with cluster variable
redhatci/ansible-collection-redhatci-ocp pull request #114
Opened 2024-01-04 09:53 UTC by ramperher

Test-Hints: assisted-abi

While testing https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92 in a disconnected environment, we could see there were conflicts with cluster variable and the output registered from some tasks, which was also called cluster.
Renaming the output to avoid these conflicts.

2024-01-04 09:53 UTC, ramperher commented
CC @tkrishtop

2024-01-04 12:32 UTC, ramperher commented
I don't get the point of the failure in the `Pull Request / Ansible-lint Check (pull_request)`, since it's complaining about code that is not being changed in this PR. I suppose that, after a green job, it should be fine to merge this.

2024-01-04 12:37 UTC, nocturnalastro submitted a review, later dismissed
LGTM

2024-01-04 13:17 UTC, tkrishtop requested changes
let's `git cherry-pick` your commit from the [main PR](https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92/commits/dd1a271758858c11250b0c12925a3454408d533a) to avoid merge conflicts later.

2024-01-04 14:40 UTC, ramperher commented
> let's `git cherry-pick` your commit from the [main PR](https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/92/commits/dd1a271758858c11250b0c12925a3454408d533a) to avoid merge conflicts later.

done

2024-01-04 14:42 UTC, ramperher commented on roles/add_day2_node/tasks/main.yml
> -        inventory_nodes:
inventory_nodes is not used in patch_host_config, that's why I've removed it.

2024-01-04 14:46 UTC, nocturnalastro commented on roles/add_day2_node/tasks/main.yml
> +    - name: "Wait for up to 20 minutes to be ready - {{ inventory_hostname }}"
```suggestion
    - name: "Wait for up to 20 minutes host to be ready - {{ inventory_hostname }}"
```

2024-01-04 14:47 UTC, ramperher commented on roles/add_day2_node/tasks/main.yml
> +    - name: "Wait for up to 20 minutes to be ready - {{ inventory_hostname }}"
done

2024-01-04 17:17 UTC, ramperher commented
> * dci-check-change  : FAILURE tested on libvirt:assisted-abi
> * assisted-abi -> failure: https://www.distributed-ci.io/jobs/ff479cbf-101e-4686-bdd0-6449d560c608/jobStates

The job has failed in an issue that appears from time to time, I'll relaunch the job.

2024-01-05 09:06 UTC, ramperher commented
I've reviewed everything again and my impression is that the issue in the debug job may be transient, I don't think it's related to this change. Also, assisted-abi is not using the roles I've changed in this PR, it's more for assisted on-prem. I'll test both options again, to see if it's finally passing.

2024-01-05 09:58 UTC, nocturnalastro approved these changes

2024-01-05 10:47 UTC, ramperher commented
assisted-abi passed, waiting for a green assisted on-prem job (it's about to finish and it's passing now), then I'll rebase the change and merge

2024-01-05 11:53 UTC, ramperher commented
I will merge since both assisted install methods have already been validated. Last change was just a rebase.

2024-01-05 11:53 UTC, merged